language: ruby
rvm:
  - 2.3.3
env:
  - DB=postgresql
before_script:
  - psql -c 'create database share_my_ride' -U postgres
  - rails db:migrate
script:
  - bundle exec rake db:test:prepare
  - bundle exec rspec
notifications:
  - false
