
default: &default
  adapter: postgresql
  timeout: 5000
  password: ""
  username: ogomb

development:
  <<: *default
  database: share_my_ride

test:
  <<: *default
  database: share_my_ride

production:
  <<: *default
  database: share_my_ride
