
default: &default
  adapter: postgresql
  timeout: 5000
  password: ""

development:
  <<: *default
  database: share_my_ride

test:
  <<: *default
  database: share_my_ride

production:
    adapter: 'postgresql'
    encoding: 'unicode'
    host: <%= ENV['DATABASE_HOST'] %>
    database: <%= ENV['DATABASE_NAME'] %>
    username: <%= ENV['DATABASE_USER'] %>
    password: <%= ENV['DATABASE_PASSWORD'] %>
